version: "3"

services:
  php:
    build:
      context: .
      args:
        - XDEBUG_ENABLED=${XDEBUG_ENABLED-false}
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/html
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
      - XDEBUG_CONFIG=${XDEBUG_CONFIG}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "8080:80"
    command: >
      sh -c "echo 'ServerName localhost' >> /etc/apache2/apache2.conf && apache2-foreground"

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: