services:
  App\Command\CarInformationCommand:
    tags:
      - { name: 'console.command' }
  App\Command\FindSparePartByModelCommand:
    arguments:
      $sparePartRepository: '@App\CarMaster\Repository\SparePartRepository'
    tags:
      - 'console.command'