services:
  App\Command\CarInformationCommand:
    tags:
      - { name: 'console.command' }
  App\Command\FindSparePartByModelCommand:
    tags:
      - 'console.command'
  App\Command\CreateSparePart:
    tags:
      - 'console.command'
  App\Command\CreateCarOwner:
    tags:
      - 'console.command'
  App\Command\CreateCar:
    tags:
      - 'console.command'